import fs from "node:fs/promises";
import path from "node:path";
import { getUpNextVersion, bumpUpNextVersion } from "../db.js";
import { DATA_DIR } from "../paths.js";
import { getUpNextFeedSourceVersion, listUpNextProviderFeedStates } from "./upNextRepository.js";
import { getCanonicalPosterUrl } from "./mediaArtwork.js";
import { publicUpNextItems } from "./upNextService.js";

const CACHE_VERSION = 4;
const CACHE_FILE = path.join(DATA_DIR, "up-next-cache.json");
const TEMP_FILE = `${CACHE_FILE}.${process.pid}.tmp`;
const UP_NEXT_TTL_MS = 2 * 60 * 1000;
const REVALIDATE_MIN_INTERVAL_MS = 10 * 60 * 1000;
const MAX_ITEMS = 100;

let memoryCache = null;
let memoryMtimeMs = 0;
let writeChain = Promise.resolve();
let buildInFlight = null;
let lastRevalidateAt = 0;

function emptyCache() {
  return {
    version: CACHE_VERSION,
    builtAt: 0,
    sourceVersion: "",
    upNextVersion: getUpNextVersion(),
    items: [],
    sourceStatus: [],
  };
}

function normalizeCache(parsed) {
  if (Number(parsed?.version || 0) !== CACHE_VERSION) return emptyCache();
  const rawItems = Array.isArray(parsed?.items) ? parsed.items.slice(0, MAX_ITEMS) : [];
  // Only the episode identity repair is needed for the current regression.
  // Leave legacy movie/unknown rows byte-for-byte compatible until their next
  // normal projection refresh, since older movie ids were not always keys
  // generated by upNextIdentity.js.
  const mergeableItems = rawItems.filter((item) => item?.media_type === "episode");
  const passthroughItems = rawItems.filter((item) => item?.media_type !== "episode").map((item) => {
    if (item?.media_type === "movie" && !item.poster_url) {
      const canonical = getCanonicalPosterUrl({
        media_type: "movie",
        title: item.title,
        tmdb_id: item.tmdb_id,
        imdb_id: item.imdb_id,
      });
      return canonical ? { ...item, poster_url: canonical } : item;
    }
    return item;
  });
  return {
    version: CACHE_VERSION,
    builtAt: Number(parsed?.builtAt || 0),
    sourceVersion: String(parsed?.sourceVersion || ""),
    upNextVersion: Number(parsed?.upNextVersion || getUpNextVersion()),
    // Older cache snapshots can contain the same resume twice under an
    // identity-bearing key and a title-only key. Normalize known media rows
    // while leaving legacy/diagnostic entries untouched.
    items: [...publicUpNextItems(mergeableItems), ...passthroughItems].slice(0, MAX_ITEMS),
    sourceStatus: Array.isArray(parsed?.sourceStatus) ? parsed.sourceStatus : [],
  };
}

async function readCache() {
  try {
    const stat = await fs.stat(CACHE_FILE);
    if (memoryCache && memoryMtimeMs === stat.mtimeMs) return memoryCache;
    const parsed = JSON.parse(await fs.readFile(CACHE_FILE, "utf8"));
    memoryCache = normalizeCache(parsed);
    memoryMtimeMs = stat.mtimeMs;
    return memoryCache;
  } catch (error) {
    if (error?.code !== "ENOENT") console.error("Failed to read Up Next cache", error);
    memoryCache = emptyCache();
    memoryMtimeMs = 0;
    return memoryCache;
  }
}

function normalizedItems(items) {
  return (Array.isArray(items) ? items : []).slice(0, MAX_ITEMS);
}

function comparableSourceStatus(status = []) {
  return (Array.isArray(status) ? status : []).map((feed) => ({
    provider: feed.provider,
    feed_kind: feed.feed_kind,
    status: feed.status,
    item_count: feed.item_count,
    complete: feed.complete,
    last_error: feed.last_error,
  }));
}

async function storeCache(result, fallbackSourceVersion) {
  const projection = result && !Array.isArray(result) && typeof result === "object"
    ? result
    : { items: result };
  const nextItems = normalizedItems(projection.items);
  let stored;
  writeChain = writeChain.catch(() => {}).then(async () => {
    const current = await readCache();
    const nextSourceStatus = Array.isArray(projection.sourceStatus) ? projection.sourceStatus : [];
    const changed = !current.builtAt
      || JSON.stringify({ items: current.items, sourceStatus: comparableSourceStatus(current.sourceStatus) })
        !== JSON.stringify({ items: nextItems, sourceStatus: comparableSourceStatus(nextSourceStatus) });
    const currentGlobalVersion = getUpNextVersion();
    const cachedVersion = Number(current.upNextVersion || 0);
    const upNextVersion = changed
      ? (currentGlobalVersion > cachedVersion ? currentGlobalVersion : bumpUpNextVersion())
      : Math.max(cachedVersion || 1, currentGlobalVersion);
    const now = Date.now();
    const next = {
      version: CACHE_VERSION,
      builtAt: now,
      sourceVersion: String(projection.sourceVersion || fallbackSourceVersion || getUpNextFeedSourceVersion()),
      upNextVersion,
      items: nextItems,
      sourceStatus: nextSourceStatus,
    };
    await fs.mkdir(DATA_DIR, { recursive: true });
    await fs.writeFile(TEMP_FILE, JSON.stringify(next), "utf8");
    await fs.rename(TEMP_FILE, CACHE_FILE);
    memoryCache = next;
    memoryMtimeMs = 0;
    stored = { ...next, changed };
  });
  await writeChain;
  return stored;
}

function buildAndStore(build) {
  if (buildInFlight) return buildInFlight;
  buildInFlight = Promise.resolve()
    .then(() => build())
    .then((result) => storeCache(result, getUpNextFeedSourceVersion()))
    .finally(() => { buildInFlight = null; });
  return buildInFlight;
}

function publicSnapshot(cache, stale = false, sourceStatus = cache.sourceStatus) {
  return {
    items: cache.items,
    builtAt: cache.builtAt,
    upNextVersion: cache.upNextVersion,
    sourceVersion: cache.sourceVersion,
    sourceStatus,
    stale,
  };
}

function currentPublicSourceStatus() {
  return listUpNextProviderFeedStates().map((feed) => {
    const publicFeed = { ...feed };
    delete publicFeed.cursor;
    return publicFeed;
  });
}

function queueBackgroundRebuild(build) {
  if (Date.now() - lastRevalidateAt < REVALIDATE_MIN_INTERVAL_MS) return false;
  lastRevalidateAt = Date.now();
  buildAndStore(build)
    .then((result) => {
      console.log(`Up Next cache background rebuild complete: ${result.items.length} item${result.items.length === 1 ? "" : "s"}${result.changed ? ", cache updated" : ", unchanged"}.`);
    })
    .catch((error) => {
      console.warn(`Up Next cache background rebuild failed: ${error.message}`);
    });
  return true;
}

// Return a warm snapshot immediately when possible. `revalidate` is used by
// the dashboard: stale data remains visible while one deduplicated rebuild
// runs behind the request. Explicit `refresh` keeps the existing manual retry
// semantics and waits for a fresh snapshot.
export async function getUpNextCacheSnapshot(build, { refresh = false, revalidate = false } = {}) {
  if (refresh) return publicSnapshot(await buildAndStore(build));

  const cache = await readCache();
  if (!cache.builtAt) return publicSnapshot(await buildAndStore(build));

  const sourceVersion = getUpNextFeedSourceVersion();
  const stale = sourceVersion !== cache.sourceVersion || Date.now() - cache.builtAt >= UP_NEXT_TTL_MS;
  if (!stale) return publicSnapshot(cache);
  if (revalidate) {
    queueBackgroundRebuild(build);
    return publicSnapshot(cache, true, currentPublicSourceStatus());
  }
  return publicSnapshot(await buildAndStore(build));
}
